### ISSUE TITLE
Pulsar Spark cannot work with Spark 2.3. Build fails.

### ISSUE THREAD

**Issue by smdahmed** [streamnative/pulsar-spark#23]
@sijie and @yjshen:

It is not currently possible to use pulsar spark module with Spark 2.3.x. Builds fails with the below trace.

```bash
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/JSONParser.scala:364: value encoding is not a member of org.apache.spark.sql.catalyst.json.JSONOptions
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:27: object JSONOptionsInRead is not a member of package org.apache.spark.sql.catalyst.json
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:29: object ContinuousInputPartition is not a member of package org.apache.spark.sql.sources.v2.reader
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:30: object ContinuousInputPartitionReader is not a member of package org.apache.spark.sql.sources.v2.reader.streaming
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:49: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:79: not found: type InputPartition
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:108: not found: type InputPartition
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:149: not found: type ContinuousInputPartition
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:148: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:156: not found: type InputPartitionReader
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:252: not found: type ContinuousInputPartitionReader
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:251: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:174: not found: type InputPartitionReader
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala:229: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarDeserializer.scala:37: object JSONOptionsInRead is not a member of package org.apache.spark.sql.catalyst.json
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarDeserializer.scala:42: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:29: object JSONOptionsInRead is not a member of package org.apache.spark.sql.catalyst.json
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:31: object InputPartition is not a member of package org.apache.spark.sql.sources.v2.reader
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:44: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:96: not found: type InputPartition
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:150: not found: type InputPartition
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:169: not found: type InputPartition
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:168: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:172: not found: type InputPartitionReader
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:193: not found: type InputPartitionReader
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:210: not found: type InputPartitionReader
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala:209: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala:27: object JSONOptionsInRead is not a member of package org.apache.spark.sql.catalyst.json
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarSource.scala:25: object JSONOptionsInRead is not a member of package org.apache.spark.sql.catalyst.json
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarSource.scala:39: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala:615: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarRelation.scala:21: object JSONOptionsInRead is not a member of package org.apache.spark.sql.catalyst.json
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarRelation.scala:40: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala:617: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala:27: object JSONOptionsInRead is not a member of package org.apache.spark.sql.catalyst.json
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala:200: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala:158: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala:43: not found: type JSONOptionsInRead
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/SchemaUtils.scala:36: value minBytesForPrecision is not a member of object org.apache.spark.sql.types.Decimal
[ERROR] [Error] /home/kabeer/code/apache/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/SchemaUtils.scala:345: not found: value minBytesForPrecision
[ERROR] 40 errors found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.981 s
[INFO] Finished at: 2019-10-30T11:55:38Z
[INFO] ------------------------------------------------------------------------

```

**To Reproduce**
1. Go to Clone the pulsar spark project
2. Change the spark.version in pom.xml to 2.3.4 (or any other valid spark 2.3.x release)
3. Run ```mvn clean package -DskipTests```

**Expected behavior**
Build should pass. 

**Additional context**
There are quite a few changes in files between Spark 2.3 and Spark 2.4. One of them which is more pertinent is: 

If you look into file for Spark 2.3 -> https://github.com/apache/spark/blob/branch-2.3/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/json/JSONOptions.scala, class JSONOptionsInRead is missing.
Whilst in Spark 2.4 -> https://github.com/apache/spark/blob/branch-2.4/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/json/JSONOptions.scala, class JSONOptionsInRead is present.

**Comment by sijie** [comment]
@yjshen can you please help with this issue?

**Comment by sijie** [comment]
@smdahmed the spark structured streaming is not well supported in spark 2.3. do you need this connector to support spark 2.3. We can consider adding a branch for supporting 2.3 if that can solve your question.

**Comment by smdahmed** [comment]
@sijie - Thank you so much for your attention to this ticket. We are going to upgrade the Spark to 2.4.x. I shall close this ticket.
